import { existsSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import robots from './robots';
import sitemap, { SITEMAP_ROUTES, siteUrl } from './sitemap';

const APP_DIR = resolve(__dirname);
const PUBLIC_DIR = resolve(__dirname, '../../public');

/** Route segments that require authentication and must never be indexed. */
const PRIVATE_PREFIXES = ['/admin', '/advertiser/', '/developer', '/auth', '/api'];

/** Every `page.tsx` under app/, as a URL path. */
function allRoutes(dir = APP_DIR, prefix = ''): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      // Route groups `(name)` and private folders `_name` do not add a segment.
      const segment = /^[([_]/.test(entry) ? '' : `/${entry}`;
      out.push(...allRoutes(full, prefix + segment));
    } else if (entry === 'page.tsx') {
      out.push(prefix === '' ? '/' : prefix);
    }
  }
  return out;
}

const isPrivate = (route: string) =>
  PRIVATE_PREFIXES.some((p) => route === p.replace(/\/$/, '') || route.startsWith(p));

describe('sitemap', () => {
  it('lists every public page — nothing ships unindexed by accident', () => {
    // The old hand-maintained public/sitemap.xml listed 5 URLs while 12 public
    // pages had shipped without ever being added. Deriving the expectation from
    // the filesystem is the only thing that stops that recurring.
    const publicRoutes = allRoutes().filter((r) => !isPrivate(r));
    const listed = new Set(SITEMAP_ROUTES.map((r) => r.path));
    const missing = publicRoutes.filter((r) => !listed.has(r));
    expect(missing, `public pages missing from sitemap.ts: ${missing.join(', ')}`).toEqual([]);
  });

  it('lists no route that does not exist — a 404 in a sitemap is an SEO penalty', () => {
    const real = new Set(allRoutes());
    const dangling = SITEMAP_ROUTES.map((r) => r.path).filter((p) => !real.has(p));
    expect(dangling, `sitemap.ts advertises non-existent routes: ${dangling.join(', ')}`).toEqual(
      [],
    );
  });

  it('never exposes an authenticated route', () => {
    const leaked = SITEMAP_ROUTES.map((r) => r.path).filter(isPrivate);
    expect(leaked, `authenticated routes leaked into the sitemap: ${leaked.join(', ')}`).toEqual(
      [],
    );
  });

  it('emits absolute URLs on the configured origin', () => {
    const entries = sitemap();
    expect(entries.length).toBe(SITEMAP_ROUTES.length);
    for (const entry of entries) {
      expect(entry.url.startsWith(`${siteUrl()}/`) || entry.url === `${siteUrl()}/`).toBe(true);
    }
  });
});

describe('robots', () => {
  it('is generated by the App Router, not shadowed by a static file', () => {
    // Files in public/ are served ahead of the App Router. A static
    // public/robots.txt saying `Allow: /` silently overrode every rule below
    // for the entire life of the project — the disallow list was written,
    // reviewed, and never actually served to a crawler.
    expect(
      existsSync(join(PUBLIC_DIR, 'robots.txt')),
      'public/robots.txt would shadow app/robots.ts — delete it',
    ).toBe(false);
    expect(
      existsSync(join(PUBLIC_DIR, 'sitemap.xml')),
      'public/sitemap.xml would shadow app/sitemap.ts — delete it',
    ).toBe(false);
  });

  it('disallows every authenticated surface', () => {
    const { rules } = robots();
    const disallow = (Array.isArray(rules) ? rules[0] : rules).disallow as string[];
    for (const prefix of ['/api/', '/auth/', '/admin/', '/developer/', '/advertiser/']) {
      expect(disallow, `crawlers must not be sent into ${prefix}`).toContain(prefix);
    }
  });

  it('keeps the public /advertiser-policy page crawlable', () => {
    // The trailing slash on `/advertiser/` is load-bearing: without it the rule
    // also blocks /advertiser-policy, a page that exists to be read.
    const { rules } = robots();
    const disallow = (Array.isArray(rules) ? rules[0] : rules).disallow as string[];
    expect(disallow).not.toContain('/advertiser');
    expect(SITEMAP_ROUTES.some((r) => r.path === '/advertiser-policy')).toBe(true);
  });

  it('points at the sitemap that actually exists', () => {
    expect(robots().sitemap).toBe(`${siteUrl()}/sitemap.xml`);
  });
});
